import dotenv from 'dotenv';

dotenv.config();

const {
  COINRISQLAB_LOG_LEVEL,
  COINRISQLAB_LOG_DIRECTORY_PATH,

  COINRISQLAB_FRONT_DOMAIN,
  COINRISQLAB_FRONT_HOSTNAME,
  COINRISQLAB_FRONT_PORT,
  COINRISQLAB_FRONT_HTTPSECURE,

  COINRISQLAB_API_HOSTNAME,
  COINRISQLAB_API_PORT,
  COINRISQLAB_API_HTTPSECURE,
  COINRISQLAB_API_JWT_SECRET,

  COINRISQLAB_DB_HOST,
  COINRISQLAB_DB_PORT,
  COINRISQLAB_DB_USER,
  COINRISQLAB_DB_PASSWORD,
  COINRISQLAB_DB_DATABASE,

  COINMARKETCAP_API_KEY,

  COINGECKO_API_KEY,

  // eslint-disable-next-line no-undef
} = process.env;

const Config = {
  COINRISQLAB_LOG_LEVEL: COINRISQLAB_LOG_LEVEL,
  COINRISQLAB_LOG_DIRECTORY_PATH: COINRISQLAB_LOG_DIRECTORY_PATH,

  COINRISQLAB_FRONT_DOMAIN: COINRISQLAB_FRONT_DOMAIN,
  COINRISQLAB_FRONT_HOSTNAME: COINRISQLAB_FRONT_HOSTNAME,
  COINRISQLAB_FRONT_PORT: COINRISQLAB_FRONT_PORT,
  COINRISQLAB_FRONT_HTTPSECURE:
    String(COINRISQLAB_FRONT_HTTPSECURE) === '1' ||
    String(COINRISQLAB_FRONT_HTTPSECURE).toLowerCase() === 'true',

  COINRISQLAB_API_HOSTNAME: COINRISQLAB_API_HOSTNAME,
  COINRISQLAB_API_PORT: COINRISQLAB_API_PORT,
  COINRISQLAB_API_HTTPSECURE:
    String(COINRISQLAB_API_HTTPSECURE) === '1' ||
    String(COINRISQLAB_API_HTTPSECURE).toLowerCase() === 'true',
  COINRISQLAB_API_JWT_SECRET: COINRISQLAB_API_JWT_SECRET,

  COINRISQLAB_DB_HOST: COINRISQLAB_DB_HOST,
  COINRISQLAB_DB_PORT: COINRISQLAB_DB_PORT,
  COINRISQLAB_DB_USER: COINRISQLAB_DB_USER,
  COINRISQLAB_DB_PASSWORD: COINRISQLAB_DB_PASSWORD,
  COINRISQLAB_DB_DATABASE: COINRISQLAB_DB_DATABASE,

  COINMARKETCAP_API_KEY: COINMARKETCAP_API_KEY,

  COINGECKO_API_KEY: COINGECKO_API_KEY,
};

export default Config;
