import PDFDocument from 'pdfkit';

const COLORS = {
  primary: '#FF6B35',
  dark: '#1a1a2e',
  text: '#333333',
  lightGray: '#f5f5f5',
  green: '#16C784',
  red: '#EA3943',
};

/**
 * Create report header with title and date.
 */
export function addHeader(doc, title, subtitle) {
  doc.fontSize(24).fillColor(COLORS.primary).text('CoinRisqLab', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(16).fillColor(COLORS.dark).text(title, { align: 'center' });
  if (subtitle) {
    doc.fontSize(10).fillColor(COLORS.text).text(subtitle, { align: 'center' });
  }
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(COLORS.primary).lineWidth(1).stroke();
  doc.moveDown(1);
}

/**
 * Add a section title.
 */
export function addSectionTitle(doc, title) {
  doc.fontSize(14).fillColor(COLORS.dark).text(title);
  doc.moveDown(0.3);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').lineWidth(0.5).stroke();
  doc.moveDown(0.5);
}

/**
 * Add a key-value row.
 */
export function addMetricRow(doc, label, value, color = COLORS.text) {
  const y = doc.y;
  doc.fontSize(10).fillColor(COLORS.text).text(label, 50, y, { width: 250 });
  doc.fontSize(10).fillColor(color).text(String(value), 300, y, { width: 245, align: 'right' });
  doc.moveDown(0.4);
}

/**
 * Add a simple table.
 */
export function addTable(doc, headers, rows, colWidths) {
  const startX = 50;
  const totalWidth = colWidths.reduce((a, b) => a + b, 0);

  // Check page break
  if (doc.y > 680) {
    doc.addPage();
  }

  // Header row
  let x = startX;
  const headerY = doc.y;
  doc.rect(startX, headerY - 2, totalWidth, 18).fillColor(COLORS.lightGray).fill();

  x = startX;
  for (let i = 0; i < headers.length; i++) {
    doc.fontSize(8).fillColor(COLORS.dark).text(headers[i], x + 4, headerY + 2, {
      width: colWidths[i] - 8,
      align: i === 0 ? 'left' : 'right',
    });
    x += colWidths[i];
  }

  doc.y = headerY + 20;

  // Data rows
  for (const row of rows) {
    if (doc.y > 720) {
      doc.addPage();
    }

    x = startX;
    const rowY = doc.y;
    for (let i = 0; i < row.length; i++) {
      const val = row[i];
      const color = typeof val === 'string' && val.startsWith('-') ? COLORS.red
        : typeof val === 'string' && val.startsWith('+') ? COLORS.green
        : COLORS.text;

      doc.fontSize(8).fillColor(color).text(String(val), x + 4, rowY, {
        width: colWidths[i] - 8,
        align: i === 0 ? 'left' : 'right',
      });
      x += colWidths[i];
    }
    doc.y = rowY + 16;
  }

  doc.moveDown(0.5);
}

/**
 * Add footer with generation date.
 */
export function addFooter(doc) {
  const bottom = doc.page.height - 40;
  doc.fontSize(7).fillColor('#999')
    .text(`Generated by CoinRisqLab on ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`, 50, bottom, {
      align: 'center',
      width: 495,
    });
}

/**
 * Create a new PDF document configured for reports.
 */
export function createReportDoc() {
  return new PDFDocument({
    size: 'A4',
    margins: { top: 40, bottom: 50, left: 50, right: 50 },
    info: {
      Title: 'CoinRisqLab Portfolio Report',
      Author: 'CoinRisqLab',
    },
  });
}
