const COINRISQLAB_API_PORT = process.env.NEXT_PUBLIC_COINRISQLAB_API_PORT;
const COINRISQLAB_API_HOSTNAME = process.env.NEXT_PUBLIC_COINRISQLAB_API_HOSTNAME;
const COINRISQLAB_API_HTTPSECURE =
  String(process.env.NEXT_PUBLIC_COINRISQLAB_API_HTTPSECURE) === "1" ||
  String(process.env.NEXT_PUBLIC_COINRISQLAB_API_HTTPSECURE).toLowerCase() ===
    "true";

export { COINRISQLAB_API_PORT, COINRISQLAB_API_HOSTNAME, COINRISQLAB_API_HTTPSECURE };
