import {
  COINRISQLAB_API_PORT,
  COINRISQLAB_API_HOSTNAME,
  COINRISQLAB_API_HTTPSECURE,
} from "./config";

export const API_BASE_URL = `http${COINRISQLAB_API_HTTPSECURE ? "s" : ""}://${COINRISQLAB_API_HOSTNAME}${COINRISQLAB_API_HTTPSECURE ? "" : `:${COINRISQLAB_API_PORT}`}`;
