export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "CoinRisqLab",
  description:
    "Free real-time crypto analytics platform. Track the top 80 cryptocurrencies with our market-cap weighted index, portfolio volatility analysis, risk metrics (VaR, Beta, Sharpe Ratio), and Fear & Greed data.",
  navItems: [
    {
      label: "Dashboard",
      href: "/",
    },
  ],
  navMenuItems: [
    {
      label: "Dashboard",
      href: "/",
    },
  ],
  siteUrl: "https://coinrisqlab.com",
  keywords: [
    "bitcoin",
    "ethereum",
    "solana",
    "crypto",
    "cryptocurrency",
    "crypto index",
    "crypto market cap",
    "coinrisqlab",
    "coinrisqlab 80 index",
    "crypto analytics",
    "crypto risk metrics",
    "market volatility",
    "portfolio volatility",
    "bitcoin volatility",
    "ethereum volatility",
    "crypto VaR",
    "value at risk crypto",
    "crypto beta",
    "crypto sharpe ratio",
    "fear and greed index",
    "crypto fear greed",
    "crypto dashboard",
    "real-time crypto data",
    "cryptocurrency analysis",
    "crypto portfolio risk",
    "digital asset index",
    "bitcoin risk",
    "ethereum risk",
    "crypto risk analysis",
    "crypto market index",
    "top 80 crypto",
    "market cap weighted index",
    "crypto volatility tracker",
    "bitcoin analytics",
    "ethereum analytics",
    "altcoin risk",
    "crypto risk management",
    "crypto correlation",
    "crypto drawdown",
    "defi risk metrics",
  ],
  authors: [
    {
      name: "CoinRisqLab Team",
      url: "https://coinrisqlab.com",
    },
  ],
  creator: "CoinRisqLab Team",
  links: {
    github: "https://github.com/coinrisqlab",
    twitter: "https://twitter.com/coinrisqlab",
  },
};
